openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:

  /sources:
    get:
      description: "get all sources"
      responses:
        200:
          description: "OK"


  /source:
    post:
      description: "add new user"
      requestBody:
        content:
          application/json:
            schema: # Request body contents
              type: object
              properties:
                name:
                  type: string
                url:
                  type: string
              example:
                url: https://google.com
                name: google
      responses:
        '201':
          description: OK




  /:
    get:
      description: "Hello World!"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
components:
  schemas:
